CREATE DATABASE IF NOT EXISTS MASTER_PYTHON;
USE MASTER_PYTHON

CREATE TABLE USUARIOS(
ID          INT AUTO_INCREMENT NOT NULL,
NOMBRE      VARCHAR(100),
APELLIDO    VARCHAR(255),
EMAIL       VARCHAR(255) NOT NULL,
PASSWORD    VARCHAR(255) NOT NULL,
FECHA       DATE NOT NULL,
CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
CONSTRAINT UQ_EMAIL UNIQUE(EMAIL)
) ENGINE = InnoDB;

CREATE TABLE NOTAS(
ID          INT AUTO_INCREMENT NOT NULL,
USUARIO_ID  INT NOT NULL,
TITULO      VARCHAR(255) NOT NULL,
NOTA        MEDIUMTEXT,
FECHA       DATE NOT NULL,
CONSTRAINT PK_ID PRIMARY KEY(ID),
CONSTRAINT FK_USUARIO FOREIGN KEY(USUARIO_ID) REFERENCES USUARIOS(ID)
) ENGINE = InnoDB;